#!/usr/bin/env python3
"""
gen_gba_layout.py -- freeze the decompilation's struct layout into assertions.

The problem
-----------
The game's structures are not private to the C code.  They are read out of the
ROM, and they are placed at addresses linker.ld chose:

    struct ToneData is the sound bank, read straight from the cartridge.  On
    the GBA it is 12 bytes with `wav` at offset 4.  Built for x86-64 it is 24
    bytes with `wav` at offset 8, so every instrument is read from the wrong
    place -- and nothing reports it.  The game boots, renders, and is wrong.

    struct Kirby is an array at 0x00020EE0 with an extent linker.ld fixed.  A
    wider struct runs over its neighbour and the game's own task allocator and
    the port disagree about where objects live.

There is no run-time symptom that points back at the cause, which is why
CMakeLists.txt refuses to configure a build with 8-byte pointers at all.  That
guard is coarse: it can say "this ABI is wrong" and nothing about *what* it
would break, and it cannot see a struct that changed shape for some other
reason -- an upstream decompilation edit, a packing attribute, a member
retyped from u32 to a pointer.

So this generator records what the layout actually is, from a build that is
known good, and emits a `PORT_LAYOUT_ASSERT` for every size and every member
offset.  After that a build either matches the console or fails to compile,
naming the struct and the member.  That is worth having whether or not the
64-bit work ever happens: it is the only thing standing between a silent
layout change and a game that is subtly wrong forever.

Where the numbers come from
---------------------------
Not from katam.elf.  It carries .debug_info and modern tools reject it: agbcc
is gcc 2.95 and gdb stops at `unexpected tag 'DW_TAG_imported_declaration'`
before reading a single type.

They come from the working 32-bit builds instead.  This tool compiles one
translation unit that includes every header in the portified tree, with the
port's own flags, and reads the layout back out of the DWARF (tools/dwarf_layout.py).
The default compiler is the i686 one; wasm32, armhf and mingw32 then *check*
the result by compiling the assertions, which is a stronger arrangement than
measuring four times would be -- three of the port's four builds are witnesses
rather than sources, and any disagreement is a build failure rather than a
number in a file nobody reads.

Types that already have the same layout in ILP32 and LP64 are asserted too.
Working out which structures are genuinely constrained is the hard direction of
this question and getting it wrong is silent; asserting all of them costs
nothing at run time and cannot be wrong.
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import dwarf_layout as D


HEADER_NOTE = """\
/* Generated by tools/gen_gba_layout.py -- do not edit.
 *
 * Every size and every member offset of every structure the decompilation
 * defines, measured from the port's ILP32 build and asserted here so that any
 * build which disagrees fails to compile instead of running and being wrong.
 *
 * Regenerate with `make layout` after the decompilation changes a structure on
 * purpose, and read the diff: a changed number here is a changed memory layout,
 * and the game's structures live at addresses linker.ld chose and are read out
 * of the ROM.  See docs/SIXTYFOUR.md.
 *
 * Bitfield members carry no offsetof and are listed in comments with their bit
 * position; the containing structure's size is asserted, which is what a
 * bitfield layout change would move.
 */
"""


def build_probe(tree, out_path):
    """One TU that includes every header in the portified tree.

    Deliberately every header rather than the ones some list names: a structure
    that stops being included anywhere would otherwise drop out of the table
    silently, and a dropped assertion is exactly the failure this file exists
    to prevent.
    """
    inc = tree / 'include'
    headers = sorted(p.relative_to(inc).as_posix() for p in inc.rglob('*.h'))
    body = ['/* generated by tools/gen_gba_layout.py; not kept */']
    body += ['#include "%s"' % h for h in headers]
    body.append('')
    out_path.write_text('\n'.join(body) + '\n')
    return headers


def measure(tree, cc, cflags, keep_obj=None):
    with tempfile.TemporaryDirectory() as td:
        probe = Path(td) / 'layout_probe.c'
        obj = Path(td) / 'layout_probe.o'
        build_probe(tree, probe)
        cmd = ([cc] + cflags +
               ['-g', '-fno-eliminate-unused-debug-types',
                '-c', str(probe), '-o', str(obj)])
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stdout + r.stderr)
            sys.exit('gen_gba_layout: the probe translation unit did not '
                     'compile.\n  %s' % ' '.join(cmd))
        if keep_obj:
            Path(keep_obj).write_bytes(obj.read_bytes())
        dw = D.Dwarf(obj)
        # DW_AT_decl_file is whatever the -I path made it, which is relative to
        # the directory the compiler ran in.  Resolve both sides rather than
        # matching on a substring: an absolute --tree against relative decl
        # paths would silently match nothing and write an empty table.
        inc = (tree / 'include').resolve()

        def from_the_game(f):
            if not f:
                return False
            try:
                return inc in Path(f).resolve().parents
            except OSError:
                return False

        types = D.collect(dw, keep_file=from_the_game)
        if not types:
            sys.exit('gen_gba_layout: the probe compiled but no structure in it '
                     'came from\n  %s -- nothing would be asserted.  Check '
                     '--tree and the include flags.' % inc)
        return dw, types


def render(types, tree):
    """The committed header: the includes, then the assertions."""
    files = sorted({t['file'] for t in types.values() if t['file']})
    inc = (tree / 'include').as_posix()
    rel = []
    for f in files:
        # decl_file paths are as the compiler saw them, relative to the build
        # directory; reduce them to what an #include line would say.
        i = f.find('/include/')
        rel.append(f[i + len('/include/'):] if i >= 0 else f)
    rel = sorted(set(rel))

    lines = [HEADER_NOTE,
             '#ifndef GUARD_PORT_GBA_LAYOUT_H',
             '#define GUARD_PORT_GBA_LAYOUT_H',
             '',
             '#include <stddef.h>

#ifdef __cplusplus
#define PORT_LAYOUT_ASSERT(cond, msg) static_assert(cond, msg)
#else
#define PORT_LAYOUT_ASSERT(cond, msg) _Static_assert(cond, msg)
#endif',
             '']
    for h in rel:
        lines.append('#include "%s"' % h)
    lines.append('')

    n_types = n_offsets = n_bitfields = 0
    for (kind, name) in sorted(types):
        t = types[(kind, name)]
        if t.get('conflict'):
            lines.append('/* %s %s: two different definitions in one build -- '
                         'not asserted */' % (kind, name))
            continue
        n_types += 1
        where = t['file']
        i = where.find('/include/') if where else -1
        where = where[i + len('/include/'):] if i >= 0 else (where or '?')
        lines.append('/* %s %s -- %s:%s */' % (kind, name, where, t['line']))
        lines.append('PORT_LAYOUT_ASSERT(sizeof(%s %s) == %d,'
                     ' "%s %s changed size -- it is read at a fixed address");'
                     % (kind, name, t['size'], kind, name))
        for mname, off, bits, _ptr in t['members']:
            if bits is not None:
                n_bitfields += 1
                lines.append('/*     %s: bitfield at bit %d, %d bits */'
                             % (mname, off, bits))
                continue
            n_offsets += 1
            lines.append('PORT_LAYOUT_ASSERT(offsetof(%s %s, %s) == %d,'
                         ' "%s %s::%s moved");'
                         % (kind, name, mname, off, kind, name, mname))
        lines.append('')

    lines.append('#endif')
    return '\n'.join(lines) + '\n', n_types, n_offsets, n_bitfields


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tree', required=True, type=Path,
                    help='portified source tree (build/port-src)')
    ap.add_argument('--out', required=True, type=Path,
                    help='the committed assertion header')
    ap.add_argument('--cc', default=os.environ.get('CC', 'gcc'))
    ap.add_argument('--cflags', default='',
                    help='the port\'s compile flags, as one string')
    ap.add_argument('--check', action='store_true',
                    help='do not write; fail if the file on disk is out of date')
    ap.add_argument('--keep-obj', help='keep the probe object (for debugging)')
    args = ap.parse_args()

    cflags = args.cflags.split()
    dw, types = measure(args.tree, args.cc, cflags, args.keep_obj)

    if dw.addr_size != 4:
        sys.exit('gen_gba_layout: %s with those flags has %d-byte pointers.\n'
                 '  The table records what the GBA layout *is*, so it has to be '
                 'measured from an\n  ILP32 build.  Pass the 32-bit flags '
                 '(-m32, or an armhf/i686 compiler).' % (args.cc, dw.addr_size))

    text, n_types, n_offsets, n_bitfields = render(types, args.tree)

    n_ptr = sum(1 for t in types.values() if any(m[3] for m in t['members']))
    conflicts = [k for k, v in types.items() if v.get('conflict')]

    if args.check:
        if not args.out.exists():
            sys.exit('gen_gba_layout: %s does not exist; run `make layout`'
                     % args.out)
        if args.out.read_text() != text:
            sys.exit('gen_gba_layout: %s is out of date.\n'
                     '  The decompilation has changed a structure.  Run '
                     '`make layout`, read the diff,\n  and commit it only if '
                     'the change is deliberate -- these are the layouts the '
                     'ROM\n  and linker.ld are written against.' % args.out)
        print('gen_gba_layout: %s is up to date (%d types, %d offsets)'
              % (args.out, n_types, n_offsets))
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print('gen_gba_layout: %d types, %d member offsets, %d bitfields'
          % (n_types, n_offsets, n_bitfields))
    print('  %d of the %d carry a pointer, so LP64 would change their layout'
          % (n_ptr, n_types))
    if conflicts:
        print('  %d SKIPPED -- defined twice with different layouts:' % len(conflicts))
        for kind, name in sorted(conflicts):
            print('      %s %s' % (kind, name))
    print('  -> %s' % args.out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
